### ISSUE TITLE
Image pixelation

### ISSUE THREAD

**Issue by ellick53** [bozcani/auairdataset#4]
Hello,

And thanks for sharing the dataset. I wonder why are the images oddly pixelated? They have squares with gradient-like patterns. 

I'd like to use your dataset for SLAM, but such image artifacts would likely break it.

**Comment by bozcani** [comment]
Hi @ellick53,

Thanks for the comment, could you please share some samples?

The problem is, probably, because of the drone's camera and gimbal. The drone (Parrot Bebop2) has built-in gimbal for its camera, and when the drone starts a movement, the gimbal adjusts the camera. During the adjustment (should be less than 1 sec), captured frames may be distorted.

**Comment by ellick53** [comment]
See below for an example. The first image is from TUM RGB-D (low resolution, but clean) and the second is a random frame from yours (the whole dataset seems to be affected).

Do you see the squares? Seems more like wonky image compression artifacts or some oddity with the sensor. I added a zoom on yours. It seems that the whole dataset is like that. 


![rgbd_dataset_freiburg2_xyz-rgb](https://user-images.githubusercontent.com/49749099/82447696-ed060780-9aa8-11ea-9024-0a125022f4e7.png)
![images_squares](https://user-images.githubusercontent.com/49749099/82447588-c942c180-9aa8-11ea-808b-0dacc1f05f23.png)

**Comment by ellick53** [comment]
I just thought of another reason: the specs say 14M image and 1920x1080 video (2M), so it may very well be a binning artifact.

**Comment by bozcani** [comment]
I agree. It is because of camera resolution.

**Comment by ellick53** [comment]
In any case, I might still be able to do something as I have to downsample the images, anyway. Do you have the camera calibration data?

**Comment by bozcani** [comment]
Yes, I should have it. I will get access to the drone on 26th May. I will let you know when I have it.

**Comment by bozcani** [comment]
Hey @ellick53,
I have these two files available, and they are coming from the ROS driver of the drone (Parrot Bebop 2). The problem is that I don't use ROS to record data, I just save it on-board memory. Therefore, these files may be useless for you. In any case, I dropped them here for you:
https://bozcani.github.io/assets/documents/bebop1_camera_calib.yaml (for image size of 640x368)
https://bozcani.github.io/assets/documents/bebop2_camera_calib.yaml (for image size of 856x480)

**Comment by bozcani** [comment]
Closed this issue for now due to inactivity, I hope the calibration files gives you an idea. Feel free to reopen it or contact me for further questions.
